// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5IRuR9PAvwRZzbUcLlRXr7iSkHjEobcs',
    appId: '1:247730670466:web:5d195e3ccf6f9a05a05d9b',
    messagingSenderId: '247730670466',
    projectId: 'diabeta-e2bfe',
    authDomain: 'diabeta-e2bfe.firebaseapp.com',
    databaseURL: 'https://diabeta-e2bfe-default-rtdb.firebaseio.com',
    storageBucket: 'diabeta-e2bfe.appspot.com',
    measurementId: 'G-HVPDDELR0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ZrNeRH6i2FqLkWfQvdEBJR0glLmLqRU',
    appId: '1:247730670466:android:4348a6ed394223efa05d9b',
    messagingSenderId: '247730670466',
    projectId: 'diabeta-e2bfe',
    databaseURL: 'https://diabeta-e2bfe-default-rtdb.firebaseio.com',
    storageBucket: 'diabeta-e2bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcQtXDuf_2PfRMyMWRkfrSgHlaQF2oNwc',
    appId: '1:247730670466:ios:b33e66d123772576a05d9b',
    messagingSenderId: '247730670466',
    projectId: 'diabeta-e2bfe',
    databaseURL: 'https://diabeta-e2bfe-default-rtdb.firebaseio.com',
    storageBucket: 'diabeta-e2bfe.appspot.com',
    iosClientId: '247730670466-tc414ncddkil5kqcqvqrsn7r4nlo2m9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabetaApp',
  );
}
